name: Export naar PDF

on:
  workflow_dispatch:

jobs:
    export:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout source repository
          uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
          with:
            ref: main
            fetch-depth: 0
        - name: Set up Python 3.11.0
          uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
          with:
            python-version: 3.13.7
  
        - name: install dependencies
          run: pip3 install -r .github/workflows/scripts/Confluence-requirements.txt
  
        - name: create services overview
          run: python3 .github/workflows/scripts/Confluence-FO-Export.py ${{ secrets.CONFLUENCE_TOKEN }} services